# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ccd7a0e4a262b524afb70471a01b7dc2b4520990dd5dfa704d3a7da0ec9fefa532f0df649471a4d3f78d1483da009241a16e994b49e63c11e4be04d94b986e65

test:
  secret_key_base: af70a9f4b4145947f7eaa897755a0485fe710842a37ae3e3b41cfc8bed2e5e885dbc279500c7b3961ed5095106682a87e70d88c399e4172150f293775306714f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
